# SOURCE: https://install.portworx.com/?operator=true&mc=false&kbver=1.25.14&b=true&iop=6&kd=%2Fdev%2Fsda&r=17001&c=px-cluster-60332ee3-f263-4175-b28b-9b15e246bb61&osft=true&stork=true&csi=true&mon=true&tel=false&st=k8s&promop=true
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-60332ee3-f263-4175-b28b-9b15e246bb61
  namespace: kube-system
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&kbver=1.25.14&b=true&iop=6&kd=%2Fdev%2Fsda&r=17001&c=px-cluster-60332ee3-f263-4175-b28b-9b15e246bb61&osft=true&stork=true&csi=true&mon=true&tel=false&st=k8s&promop=true"
    portworx.io/is-openshift: "true"
spec:
  image: portworx/oci-monitor:3.1.6
  imagePullPolicy: Always
  kvdb:
    internal: true
  storage:
    useAll: true
    kvdbDevice: /dev/sda
  deleteStrategy:
    type: UninstallAndWipe
  secretsProvider: k8s
  startPort: 17001
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  runtimeOptions:
    default-io-profile: "6"
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: false
    prometheus:
      enabled: true
      exportMetrics: true